# Generated by Django 4.1.5 on 2023-02-05 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('methodist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
