# Generated by Django 4.1.5 on 2023-02-05 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('methodist', '0002_department_created_department_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
    ]
