# Generated by Django 4.1.5 on 2023-02-06 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('methodist', '0003_alter_department_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name educational programs')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_programs', to='methodist.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Educational program',
                'verbose_name_plural': 'Educational programs',
            },
        ),
    ]
